name: Generate Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@master
    
    - name: Build Executables
      run: |
        swift build -c release --build-path protoc-gen-swift-build
      
    - name: Compress Artifacts
      run: |
        tar -czf protoc-gen-swift.tgz protoc-gen-swift-build/release/protoc-gen-swift*

    - uses: actions/upload-artifact@master
      with:
        name: protoc-gen-swift-artifacts
        path: protoc-gen-swift.tgz
